PackageTracking.Web/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PackageTracking.Data;

namespace PackageTracking.Web.Controllers
{
    public class ClientsController : WebController
    {
        public ClientsController(PackageTrackingContext packageTrackingContext) : base(packageTrackingContext)
        {
        }

        public ActionResult Index(bool? showDisabled)
        {
            var query = _packageTrackingContext.Client.AsQueryable();
            if (showDisabled == false)
            {
                query = query.Where(c => c.Enabled);
            }
            query = query.OrderBy(c => c.Name);
            return View(query.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientId,Name,Address,Note")] Client client)
        {
            if (ModelState.IsValid)
            {
                client.Enabled = true;
                _packageTrackingContext.Client.Add(client);
                _packageTrackingContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = _packageTrackingContext.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientId,Name,Address,Note,Enabled")] Client client)
        {
            if (ModelState.IsValid)
            {
                _packageTrackingContext.Client.Attach(client);
                _packageTrackingContext.Entry(client).State = EntityState.Modified;
                _packageTrackingContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        //todo - move to ajax call
        public ActionResult Enable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = _packageTrackingContext.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            client.Enabled = !client.Enabled;
            _packageTrackingContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PackageTracking.Web/Controllers/WarehousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PackageTracking.Data;

namespace PackageTracking.Web.Controllers
{
    public class WarehousesController : WebController
    {
        public WarehousesController(PackageTrackingContext packageTrackingContext) : base(packageTrackingContext)
        {
        }

        // GET: Warehouses
        public ActionResult Index()
        {
            throw new NotSupportedException("Do not use this action for Warehouses.");
        }

        // GET: Warehouses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Warehouse warehouse = _packageTrackingContext.Warehouse.Find(id);
            if (warehouse == null)
            {
                return HttpNotFound();
            }
            return View(warehouse);
        }

        // GET: Warehouses/Create
        public ActionResult Create(int clientId)
        {
            var warehouse = new Warehouse
            {
                Client = _packageTrackingContext.Client.Find(clientId)
            };
            return View(warehouse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WarehouseId,ClientId,Name,Email,PhoneNumber,Skype,Telegram,Address," +
            "WorkingTime,ResponsiblePerson")] Warehouse warehouse)
        {
            if (ModelState.IsValid)
            {
                warehouse.Enabled = true;
                _packageTrackingContext.Warehouse.Add(warehouse);
                _packageTrackingContext.SaveChanges();
                return RedirectToAction("Edit", "Clients", new { id = warehouse.ClientId });
            }
            return View(warehouse);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Warehouse warehouse = _packageTrackingContext.Warehouse.Find(id);
            if (warehouse == null)
            {
                return HttpNotFound();
            }
            return View(warehouse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WarehouseId,ClientId,Name,Email,PhoneNumber,Skype,Telegram,Address," +
            "WorkingTime,ResponsiblePerson,Enabled")] Warehouse warehouse)
        {
            if (ModelState.IsValid)
            {
                _packageTrackingContext.Warehouse.Attach(warehouse);
                _packageTrackingContext.Entry(warehouse).State = EntityState.Modified;
                _packageTrackingContext.SaveChanges();
                return RedirectToAction("Edit", "Clients", new { id = warehouse.ClientId });
            }
            return View(warehouse);
        }

        public ActionResult Enable(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var warehouse = _packageTrackingContext.Warehouse.Find(id);
            if (warehouse == null)
            {
                return HttpNotFound();
            }
            warehouse.Enabled = !warehouse.Enabled;
            _packageTrackingContext.SaveChanges();
            return RedirectToAction("Edit", "Clients");
        }
    }
}

PackageTracking.Web/Views/Clients/ClientsWarehouses.cshtml
@model PackageTracking.Data.Client
<p>
    @Html.ActionLink("Добавить", "Create", "Warehouses", new { clientId = Model.ClientId }, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creator)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Enabled)
        </th>
    </tr>

    @foreach (var item in Model.Warehouses)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Edit", "Warehouses", new { id = item.WarehouseId }, null)
            </td>
            <td>
                @item.Creator.Name
            </td>
            <td>
                @item.CreatedOn.ToLocalTime()
            </td>
            <td>
                @Html.CheckBox("Статус", item.Enabled, new { disabled = "disabled" })
                @Html.ActionLink(item.Enabled ? "Выкл" : "Вкл", "Enable", "Warehouses", new { id = item.WarehouseId }, null)
            </td>
        </tr>
    }

</table>

PackageTracking.Web/Views/Clients/Create.cshtml
@model PackageTracking.Data.Client

@{
    ViewBag.Title = "Новый клиент";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Note, new { @class = "form-control", @cols = 100, @rows=5 })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PackageTracking.Web/Views/Clients/Edit.cshtml
@model PackageTracking.Data.Client

@{
    ViewBag.Title = $"Клиент {Model.Name}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClientId)
        <div class="col-md-6">
            <h3>@ViewBag.Title</h3>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Enabled, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.CheckBoxFor(model => model.Enabled, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextAreaFor(model => model.Note, new { @class = "form-control", @cols = 100, @rows = 5 })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    <input type="submit" value="Сохранить" class="btn btn-default" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    Добавил:&nbsp;@Model.Creator.Name&nbsp;@Model.CreatedOn.ToLocalTime()
                </div>
                <div class="col-md-offset-3 col-md-9">
                    Изменил:&nbsp;@Model.Modifier.Name&nbsp;@Model.ModifiedOn.ToLocalTime()
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <h3>Склады</h3>
            @Html.Partial("ClientsWarehouses", Model)
        </div>
    </div>
}

<div class="col-md-12">
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PackageTracking.Web/Views/Clients/Index.cshtml
@model IEnumerable<PackageTracking.Data.Client>

@{
    ViewBag.Title = "Клиенты";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@ViewBag.Title</h3>
@if (!Model.Any())
{
    <p>Нет информации для отбражения.</p>
}
<p>
    @Html.ActionLink("Добавить клиента.", "Create")
</p>
@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Creator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enabled)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Name, "Edit", new { id = item.ClientId })
                </td>
                <td>
                    @Html.ActionLink(item.Address, "Edit", new { id = item.ClientId })
                </td>
                <td>
                    @item.Creator.Name
                </td>
                <td>
                    @item.CreatedOn.ToLocalTime()
                </td>
                <td>
                    @Html.CheckBox("Статус", item.Enabled, new { disabled = "disabled" })
                    @Html.ActionLink(item.Enabled ? "Выкл" : "Вкл", "Enable", new { id = item.ClientId })
                </td>
            </tr>
        }

    </table>
}